import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.0';
const supabase=createClient('https://nmcycgpwptxydxbookxw.supabase.co','sb_publishable_r39P3znJOOFew7nQVQ4Skw_ygk_xvvM');
const $=id=>document.getElementById(id);const adminEmail='sebastiansopelana@gmail.com';
let programs=[],selectedProgram=null,chapters=[],selectedChapter=null,session=null;
const say=(msg)=>{const el=$('notice');el.textContent=msg;el.style.display='block';setTimeout(()=>{if(el.textContent===msg)el.style.display='none'},5000)};
const err=e=>{console.error(e);say(e?.message||'Ocurrió un error')};
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
async function loadPublic(){const {data,error}=await supabase.from('programs').select('id,number,title,synopsis,broadcast_date,status,cover_url').order('number',{ascending:false});if(error)return err(error);programs=data||[];renderPrograms()}
async function renderPrograms(){const q=$('search').value.toLowerCase();const list=programs.filter(p=>(p.number+' '+p.title+' '+(p.synopsis||'')).toLowerCase().includes(q));$('archive-status').textContent=list.length+' programa(s) publicados';const holder=$('programs');holder.innerHTML='';for(const p of list){const box=document.createElement('section');box.className='public-program';box.innerHTML='<div class="program-number"><span>PROGRAMA</span><strong>'+p.number+'</strong></div><div class="program-intro"><h2>'+escapeHtml(p.title)+'</h2><p>'+escapeHtml(p.synopsis||'')+'</p></div><div class="public-artists" id="artists-'+p.id+'"></div>';holder.appendChild(box);const {data:chs}=await supabase.from('chapters').select('id,title,position,public_text').eq('program_id',p.id).order('position');const artists=box.querySelector('.public-artists');for(const ch of chs||[]){const {data:songs}=await supabase.from('songs').select('position,title,artist_name,album,youtube_url,selection_reason').eq('chapter_id',ch.id).order('position');const photo=musicianThumb(ch.position);artists.insertAdjacentHTML('beforeend','<article class="public-artist">'+(photo?'<div class="artist-photo">'+photo+'</div>':'')+'<div class="artist-content"><span class="kicker">HISTORIA '+ch.position+'</span><h3>'+escapeHtml(ch.title)+'</h3><div class="public-story">'+escapeHtml(ch.public_text||'')+'</div><div class="youtube-list">'+(songs||[]).map(s=>'<a class="youtube-link" href="'+escapeHtml(safeUrl(youtubeVerified[s.title]||s.youtube_url||''))+'" target="_blank" rel="noopener noreferrer"><span>▶</span><strong>'+escapeHtml(s.artist_name)+' — '+escapeHtml(s.title)+'</strong><small>ESCUCHAR EN YOUTUBE</small></a>').join('')+'</div></div></article>')}}if(!list.length)holder.innerHTML='<p>Todavía no hay programas publicados.</p>'}
const youtubeVerified={
 'T-Bone Jumps Again':'https://www.youtube.com/watch?v=pnEY_J5nADo',
 'Cold Cold Feeling':'https://www.youtube.com/watch?v=UlZRjmmTKgo',
 'T-Bone Shuffle':'https://www.youtube.com/watch?v=PwMC3W3BE4c',
 'Call It Stormy Monday':'https://www.youtube.com/watch?v=UhzAmBG96ZU',
 'Tuff Enuff':'https://www.youtube.com/watch?v=EcXT1clXc04',
 'Gangster of Love':'https://www.youtube.com/watch?v=GS_pp4D0Hlg'
};
const directYoutube=s=>{const url=youtubeVerified[s.title]||s.youtube_url||'';const m=url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([A-Za-z0-9_-]{11})/);return m?m[1]:null};
function playTrack(videoId){let holder=document.getElementById('song-video-player');if(!holder){holder=document.createElement('div');holder.id='song-video-player';holder.className='song-video-player';holder.innerHTML='<button type="button" id="close-song-player" aria-label="Cerrar reproductor">✕ Cerrar</button><div class="song-video-frame"></div>';document.body.appendChild(holder);holder.querySelector('#close-song-player').onclick=()=>{holder.remove()}}holder.querySelector('.song-video-frame').innerHTML='<iframe title="Reproductor de YouTube" src="https://www.youtube-nocookie.com/embed/'+videoId+'?autoplay=1&playsinline=1" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>';holder.scrollIntoView({behavior:'smooth',block:'center'})}
const musicianPhotos={
  1:{name:'T-Bone Walker',file:'T-Bone_Walker_1972.jpg',credit:'Heinrich Klaffs · CC BY-SA 2.0'},
  2:{name:'Clarence “Gatemouth” Brown',file:'Clarence_"Gatemouth"_Brown_with_guitar_in_the_1940s_-_Duke-Peacock_Records_publicity_photo.jpg',credit:'Fotografía promocional histórica · Wikimedia Commons'},
  3:{name:'Johnny “Guitar” Watson',file:'Johnny_Guitar_Watson_1987.jpg',credit:'Mika Väisänen · CC0'},
  4:{name:'Jimmie Vaughan',file:'Jimmie_Vaughan_by_Gage_Skidmore_2.jpg',credit:'Gage Skidmore · CC BY-SA'}
};
const musicianImage=(n)=>{const a=musicianPhotos[n];if(!a)return '';const url='https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(a.file)+'?width=640';const source='https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(a.file);return `<figure class="musician-figure"><img loading="lazy" src="${escapeHtml(url)}" alt="Fotografía documental de ${escapeHtml(a.name)}"><figcaption>Foto: <a href="${escapeHtml(source)}" target="_blank" rel="noopener noreferrer">${escapeHtml(a.credit)}</a></figcaption></figure>`};
const musicianThumb=(n)=>{const a=musicianPhotos[n];if(!a)return '';const url='https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(a.file)+'?width=320';return `<img loading="lazy" src="${escapeHtml(url)}" alt="${escapeHtml(a.name)}">`};
async function showProgram(id){const p=programs.find(x=>x.id===id);if(!p)return;const {data:chs,error}=await supabase.from('chapters').select('id,title,position,public_text').eq('program_id',id).order('position');if(error)return err(error);let html=`<button id="back">← Volver al archivo</button><div class="program-heading"><span class="kicker">ARCHIVO · PROGRAMA ${p.number}</span><h2>${escapeHtml(p.title)}</h2><p>${escapeHtml((p.synopsis||'').replace(/\s*Investigación, redacción y producción: Sebastián Sopelana\.?/gi,''))}</p></div><nav class="musician-quicknav" aria-label="Ir directamente a cada músico">`;const chapters=chs||[];for(const c of chapters){const name=musicianPhotos[c.position]?.name||c.title;html+=`<a class="musician-thumb" href="#historia-${c.position}" aria-label="Leer historia de ${escapeHtml(name)}">${musicianThumb(c.position)}<span>${escapeHtml(name)}</span></a>`}html+='</nav><div class="chapter-list">';for(const c of chapters){const {data:songs}=await supabase.from('songs').select('position,title,artist_name,album,youtube_url,selection_reason').eq('chapter_id',c.id).order('position');html+=`<article class="chapter-detail" id="historia-${c.position}"><div class="chapter-title"><h3>CAPÍTULO ${c.position} — ${escapeHtml(musicianPhotos[c.position]?.name||c.title.split(':')[0])}</h3><p class="chapter-subtitle">${escapeHtml(c.title.includes(':')?c.title.split(':').slice(1).join(':').trim():c.title)}</p></div><div class="story">${escapeHtml(c.public_text||'Historia en preparación.')}</div><h4>Cuatro canciones para esta historia</h4><div class="track-list">${(songs||[]).map(s=>`<div class="song"><strong>${escapeHtml(s.artist_name)} — ${escapeHtml(s.title)}</strong>${s.album?` · ${escapeHtml(s.album)}`:''}<p>${escapeHtml(s.selection_reason||'')}</p>${directYoutube(s)?`<button class="song-link song-play" type="button" data-video="${directYoutube(s)}">▶ ESCUCHAR</button>`:`<span class="song-pending">Audio pendiente de enlace directo</span>`}</div>`).join('')}</div></article>`}html+='</div><p class="program-credit">Investigación, redacción, producción y selección musical: <strong>Sebastián Sopelana</strong>.</p>';$('details').innerHTML=html;$('details').querySelectorAll('.song-play').forEach(btn=>btn.addEventListener('click',()=>playTrack(btn.dataset.video)));$('details').hidden=false;$('programs').hidden=true;$('details').querySelector('#back').onclick=()=>{$('details').hidden=true;$('programs').hidden=false};$('details').scrollIntoView({behavior:'smooth',block:'start'})}
function switchView(view){$('archive').hidden=view!=='archive';$('studio').hidden=view!=='studio';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='studio')checkAuth()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('search').oninput=renderPrograms;
async function checkAuth(){const {data:{session:s}}=await supabase.auth.getSession();session=s;const allowed=s?.user?.email?.toLowerCase()===adminEmail;$('login').hidden=!!allowed;$('workspace').hidden=!allowed;$('logout').hidden=!allowed;if(allowed)await loadStudio();else if(s){say('Esta cuenta no tiene acceso al estudio.');await supabase.auth.signOut()}}
$('login').onsubmit=async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('password').value='';if(error)return err(error);await checkAuth()};
$('forgot').onclick=async()=>{const email=$('email').value.trim()||adminEmail;const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/?recovery=1'});if(error)return err(error);$('auth-hint').textContent='Te enviamos el enlace de recuperación al correo.'};
$('reset-form').onsubmit=async e=>{e.preventDefault();const {error}=await supabase.auth.updateUser({password:$('new-password').value});if(error)return err(error);$('reset-form').hidden=true;say('Contraseña actualizada');await checkAuth()};
supabase.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){$('login').hidden=true;$('reset-form').hidden=false}});
$('logout').onclick=async()=>{await supabase.auth.signOut();await checkAuth()};
$('open-reader').onclick=()=>openReader();$('reader-back').onclick=()=>{$('reader').hidden=true;$('workspace').hidden=false};let readerSize=2;$('font-up').onclick=()=>{readerSize=Math.min(3.2,readerSize+.15);document.documentElement.style.setProperty('--reader-size',readerSize+'rem')};$('font-down').onclick=()=>{readerSize=Math.max(1.2,readerSize-.15);document.documentElement.style.setProperty('--reader-size',readerSize+'rem')};
async function openReader(){if(!selectedProgram)return say('Seleccioná un programa');const {data:chs,error}=await supabase.from('chapters').select('id,position,title,studio_script').eq('program_id',selectedProgram.id).order('position');if(error)return err(error);let html='<div class="reader-title"><span class="kicker">PROGRAMA '+selectedProgram.number+'</span><h1>'+escapeHtml(selectedProgram.title)+'</h1></div>';if(selectedProgram.opening_script)html+='<section class="reader-section"><h2>APERTURA</h2><div class="reader-script">'+escapeHtml(selectedProgram.opening_script)+'</div></section>';for(const x of chs||[]){const {data:songs}=await supabase.from('songs').select('position,title,artist_name').eq('chapter_id',x.id).order('position');html+='<section class="reader-section"><h2>CAPÍTULO '+x.position+' — '+escapeHtml(x.title)+'</h2><div class="reader-script">'+escapeHtml(x.studio_script||'')+'</div>'+((songs||[]).length?'<div class="reader-songs"><strong>TEMAS DEL BLOQUE</strong>'+songs.map(s=>'<p>'+s.position+'. '+escapeHtml(s.artist_name)+' — '+escapeHtml(s.title)+'</p>').join('')+'</div>':'')+'</section>'}if(selectedProgram.closing_script)html+='<section class="reader-section"><h2>CIERRE</h2><div class="reader-script">'+escapeHtml(selectedProgram.closing_script)+'</div></section>';$('reader-content').innerHTML=html;$('workspace').hidden=true;$('reader').hidden=false;scrollTo({top:0,behavior:'smooth'})}
async function loadStudio(){const {data,error}=await supabase.from('programs').select('*').order('number',{ascending:false});if(error)return err(error);const previous=selectedProgram?.id;programs=data||[];$('program-select').innerHTML='<option value="">Seleccionar…</option>'+programs.map(p=>`<option value="${p.id}">${p.number} · ${escapeHtml(p.title)}</option>`).join('');if(previous&&programs.some(p=>p.id===previous))$('program-select').value=previous;selectProgram($('program-select').value)}
function selectProgram(id){selectedProgram=programs.find(p=>p.id===id)||null;const p=selectedProgram||{};for(const [key,field] of Object.entries({number:'p-number',title:'p-title',synopsis:'p-synopsis',broadcast_date:'p-date',cover_url:'p-cover',opening_script:'p-opening',closing_script:'p-closing'}))$(field).value=p[key]||'';$('p-status').value=p.status||'draft';$('chapters-editor').hidden=!selectedProgram;$('live-panel').hidden=!selectedProgram;if(selectedProgram)loadChapters()}
$('program-select').onchange=e=>selectProgram(e.target.value);$('new-program').onclick=()=>{$('program-select').value='';selectProgram('');$('p-number').focus()};
$('save-program').onclick=async()=>{const obj={number:Number($('p-number').value),title:$('p-title').value.trim(),synopsis:$('p-synopsis').value,broadcast_date:$('p-date').value||null,status:$('p-status').value,cover_url:$('p-cover').value||null,opening_script:$('p-opening').value,closing_script:$('p-closing').value};if(!obj.number||!obj.title)return say('Completá número y título');let q=supabase.from('programs');const {data,error}=selectedProgram?await q.update(obj).eq('id',selectedProgram.id).select().single():await q.insert(obj).select().single();if(error)return err(error);selectedProgram=data;say('Programa guardado');await loadStudio();$('program-select').value=data.id;selectProgram(data.id)};
async function loadChapters(){const {data,error}=await supabase.from('chapters').select('*').eq('program_id',selectedProgram.id).order('position');if(error)return err(error);chapters=data||[];$('chapter-select').innerHTML='<option value="">Seleccionar…</option>'+chapters.map(c=>`<option value="${c.id}">${c.position} · ${escapeHtml(c.title)}</option>`).join('');selectChapter(chapters[0]?.id||'');$('chapter-select').value=selectedChapter?.id||'';const {data:live}=await supabase.from('live_state').select('*').eq('program_id',selectedProgram.id).maybeSingle();$('live-chapter').value=live?.chapter_position||1;$('live-fragment').value=live?.fragment_position||1;$('live-active').checked=!!live?.is_live}
function selectChapter(id){selectedChapter=chapters.find(c=>c.id===id)||null;const c=selectedChapter||{};$('c-position').value=c.position||Math.min(chapters.length+1,4);$('c-title').value=c.title||'';$('c-public').value=c.public_text||'';$('c-script').value=c.studio_script||'';$('songs-editor').innerHTML='';if(selectedChapter)loadSongs()}
$('chapter-select').onchange=e=>selectChapter(e.target.value);$('new-chapter').onclick=()=>{$('chapter-select').value='';selectChapter('')};
$('save-chapter').onclick=async()=>{if(!selectedProgram)return say('Primero guardá el programa');const obj={program_id:selectedProgram.id,position:Number($('c-position').value),title:$('c-title').value.trim(),public_text:$('c-public').value,studio_script:$('c-script').value};if(!obj.title||obj.position<1||obj.position>4)return say('Indicá título y posición de 1 a 4');const {data,error}=selectedChapter?await supabase.from('chapters').update(obj).eq('id',selectedChapter.id).select().single():await supabase.from('chapters').insert(obj).select().single();if(error)return err(error);await loadChapters();$('chapter-select').value=data.id;selectChapter(data.id);say('Capítulo guardado')};
async function loadSongs(){const {data,error}=await supabase.from('songs').select('*').eq('chapter_id',selectedChapter.id).order('position');if(error)return err(error);const list=[1,2,3,4].map(n=>data?.find(s=>s.position===n)||{position:n});$('songs-editor').innerHTML=list.map(s=>`<div class="songrow" data-position="${s.position}"><h4>Tema ${s.position}</h4><div class="two"><label>Artista<input class="artist" value="${escapeHtml(s.artist_name||'')}"></label><label>Canción<input class="title" value="${escapeHtml(s.title||'')}"></label></div><label>Álbum<input class="album" value="${escapeHtml(s.album||'')}"></label><label>Enlace YouTube<input class="youtube" value="${escapeHtml(s.youtube_url||'')}"></label><label>Por qué suena<textarea class="reason" rows="2">${escapeHtml(s.selection_reason||'')}</textarea></label></div>`).join('')}
$('save-songs').onclick=async()=>{if(!selectedChapter)return say('Primero guardá el capítulo');for(const el of document.querySelectorAll('.songrow')){const value=cls=>el.querySelector('.'+cls).value.trim();if(!value('title')&&!value('artist'))continue;if(!value('title')||!value('artist'))return say('Completá artista y canción');const obj={chapter_id:selectedChapter.id,position:Number(el.dataset.position),title:value('title'),artist_name:value('artist'),album:value('album')||null,youtube_url:value('youtube')||null,selection_reason:value('reason')||null};const {data:existing,error:lookupError}=await supabase.from('songs').select('id').eq('chapter_id',obj.chapter_id).eq('position',obj.position).maybeSingle();if(lookupError)return err(lookupError);const {error}=existing?await supabase.from('songs').update(obj).eq('id',existing.id):await supabase.from('songs').insert(obj);if(error)return err(error)}say('Canciones guardadas')};
$('save-live').onclick=async()=>{if(!selectedProgram)return;const obj={program_id:selectedProgram.id,chapter_position:Number($('live-chapter').value),fragment_position:Number($('live-fragment').value),is_live:$('live-active').checked,updated_at:new Date().toISOString()};const {error}=await supabase.from('live_state').upsert(obj);if(error)return err(error);say('Estado de transmisión actualizado')};
checkAuth();loadPublic();
